sudo: false

language: node_js

node_js:
  - "8.11.2"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5


before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
      export CXX="clang++-3.5";
      export CC="clang-3.5";
    fi;
  - npm install -g npm@5.6.0


install:
  - npm i --XALL
  - if [ ! -d bin-win32 ] || [ ! -d bin-win64 ] || [ ! -d bin-linux32 ] || [ ! -d bin-linux64 ] || [ ! -d bin-mac64 ]; then
      false
    fi;
  - npm i
  - if [ -d bin-win32 ] || [ -d bin-win64 ] || [ -d bin-linux32 ] || [ ! -d bin-linux64 ] || [ -d bin-mac64 ]; then
      false
    fi;
  - cd test && npm i
  - cd ..


script:
  - cd test && npm test
  - cd ..
