matrix:
  include:
    - name: "Linux Test"
      language: node_js
      node_js: "10.16.1"
      os: linux
      if: NOT commit_message =~ /^:hammer:/
      dist: xenial
      sudo: false
      install:
        - cd test
        - npm ci
    - name: "OSX Test"
      os: osx
      if: NOT commit_message =~ /^:hammer:/
      language: node_js
      node_js: "10.16.1"
      install:
        - cd test
        - npm ci
    - name: "Linux Build"
      os: linux
      dist: xenial
      sudo: required
      if: commit_message =~ /^:hammer:/
      env:
        - ISBUILD=true
        - SYSNAME=Linux
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq xorg-dev
      script:
        - chmod +x src/linux-glfw.sh && src/linux-glfw.sh
    - name: "OSX Build"
      os: osx
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: clang++
      env:
        - ISBUILD=true
        - SYSNAME=OSX
      script:
        - chmod +x src/osx-glfw.sh && src/osx-glfw.sh
        - chmod +x src/osx-glew.sh && src/osx-glew.sh


deploy:
  on:
    all_branches: true
    condition: $ISBUILD = true
  provider: releases
  name: "Binary for $SYSNAME"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file_glob: true
  file: src/build/*
