name: Build Linux GLEW

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-20.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Build
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libgl-dev dos2unix xorg-dev
          chmod +x src/linux-glew.sh && src/linux-glew.sh

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: linux-glew-${{ github.run }}-${{ github.sha }}
          name: GLEW Linux
          body: Linux GLEW binaries at ${{ github.sha }}
          files: src/build/*
