name: Build OSX GLEW

on:
  workflow_dispatch

jobs:
  Build:
    if: contains('["raub"]', github.actor)
    runs-on: macos-11

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Build
        run: |
          chmod +x src/osx-glew.sh && src/osx-glew.sh
      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: osx-glew-${{ github.run }}-${{ github.sha }}
          name: GLEW OSX
          body: OSX GLEW binaries at ${{ github.sha }}
          files: src/build/*
