name: Validate
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-20.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Run ESLint
        run: npm run eslint

  unit-tests:
    name: Unit Tests
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11, [self-hosted, linux, ARM64]]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Find libs
        if: matrix.os == 'ubuntu-20.04'
        run: |
          chmod +x src/update-linux.sh && src/update-linux.sh
          ldconfig -p | grep libGL.so
          ldconfig -p | grep libXrandr.so
          ldconfig -p | grep libXrender.so
          ldconfig -p | grep libXrandr.a
          ldconfig -p | grep libXrender.a

      - name: Build Post Step
        if: matrix.os == 'ubuntu-20.04'
        run: node src/build-post

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Run Unit Tests
        run: npm run test-ci
